# Generated by Django 2.2.9 on 2022-01-24 21:40

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('imagem', stdimage.models.StdImageField(upload_to='Categorias', verbose_name='Imagem')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('imagem', stdimage.models.StdImageField(upload_to='Depoimentos', verbose_name='Imagem')),
                ('nome', models.CharField(max_length=55, verbose_name='Nome')),
                ('depoimento', models.TextField(max_length=255, verbose_name='Depoimento')),
                ('empresa', models.CharField(max_length=55, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('nome_do_parceiro', models.CharField(max_length=255, verbose_name='Nome do parceiro')),
                ('arquivo', models.FileField(upload_to='Arquivos', verbose_name='Arquivos')),
                ('fatos', models.TextField(verbose_name='Fatos')),
            ],
            options={
                'verbose_name': 'Reclamação',
                'verbose_name_plural': 'Reclamações',
            },
        ),
        migrations.CreateModel(
            name='Renovacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Renovação',
                'verbose_name_plural': 'Renovações',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nomec', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('cpfc', models.CharField(max_length=20, verbose_name='CPF')),
                ('telefonec', models.CharField(max_length=20, verbose_name='Telefone')),
                ('emailc', models.EmailField(max_length=254, verbose_name='E-mail do cliente')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='Solicitacoes', verbose_name='Imagem')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do anúncio')),
                ('categoria', models.CharField(choices=[('salgados', 'Salgados'), ('doces', 'Doces'), ('bolos', 'Bolos'), ('bolos_fake', 'Bolos Fake'), ('estacao_de_festas', 'Estação De Festas'), ('bebidas_e_drinks', 'Bebidas e Drinks'), ('garcons', 'Garçons'), ('temas_e_decoracoes', 'Temas e Decorações'), ('lembrancinhas_personalizadas', 'Lembrancinhas Personalizadas'), ('topo_de_bolo', 'Topo de Bolo'), ('mesas_e_cadeiras', 'Mesas e Cadeiras'), ('convites', 'Convites'), ('recreacao_infantil', 'Recreação Infantil'), ('roupas_tematicas', 'Roupas Tematicas/Fantasias'), ('musica', 'Músicos/Djs'), ('fotos_e_filmagens', 'Fotos e Filmagens'), ('artigos_para_festas', 'Artigos Para Festas'), ('casa_de_festas', 'Casa de Festas')], max_length=55, verbose_name='Categorias')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
                ('estado', models.TextField(max_length=255, verbose_name='Descrição')),
                ('cidade', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('istagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('google_maps', models.TextField(blank=True, null=True, verbose_name='Google maps')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
            },
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='Promocoes', verbose_name='Imagem')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome do anúncio')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('istagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('google_maps', models.TextField(blank=True, null=True, verbose_name='Google maps')),
                ('publicado', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Bairro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categorias')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Estado')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Estado'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cidade'),
        ),
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='Anuncios', verbose_name='Imagem')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome do anúncio')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('istagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('google_maps', models.TextField(blank=True, null=True, verbose_name='Google maps')),
                ('publicado', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Bairro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categorias')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Estado')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
            },
        ),
    ]
