# Generated by Django 2.2.9 on 2021-12-21 02:11

from django.db import migrations
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagem',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, upload_to='Categorias', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
