# Generated by Django 2.2.9 on 2022-01-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Renovação',
                'verbose_name_plural': 'Renovações',
            },
        ),
        migrations.RenameField(
            model_name='anuncios',
            old_name='nome',
            new_name='titulo',
        ),
    ]
