# Generated by Django 2.2.9 on 2022-01-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220126_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocoes',
        ),
    ]
